services:
  - type: web
    name: video-hosting-api
    env: node
    buildCommand: npm install
    startCommand: node db-init.js && node server.js
    envVars:
      - key: NODE_ENV
        value: production
